### ISSUE TITLE
Backblaze B2: AUTH_API_HOST not picking up the default

### ISSUE THREAD

**Issue by nocko** [apache/libcloud#1338] opened 2019-08-07 11:03 UTC
Running the demo code in the docs:

```
from libcloud.storage.types import Provider
from libcloud.storage.providers import get_driver

account_id = 'XXXXXX'
application_key = 'YYYYYY'

cls = get_driver(Provider.BACKBLAZE_B2)
driver = cls(account_id, application_key)
driver.list_containers()
```

Produces the error:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='none', port=443): Max retries exceeded with url: /b2api/v1/b2_list_buckets?accountId=xxxxxxxxxx (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7366797610>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

```
If the host is supplied to the constructor, then it works as intended:
```
driver = cls(account_id, application_key, host='api.backblaze.com')
```

I can replicate this on Python 2 and Python 3. I am using libcloud via django-storages, so there isn't a way for me to pass the hostname via the constructor. 

Looking at the backblaze provider the default host is provided and correct, but somehow not making it into the connection object before request is called.

I can take another look at this this afternoon, but a patch didn't jump out at me immediately.

**Comment by Kami** [comment] 2019-08-07 17:06
Thanks for reporting this.

I was able to reproduce this issue. I believe it's a regression which was introduced when we moved to the ``requests`` library.

I think I know how to fix it, I will look into it.

~~On a related note - it looks like that our current Backblaze B2 driver only support master key auth ant not application key auth. I will add this info to the documentation.~~

**Comment by Kami** [comment] 2019-08-09 13:42
#1339 which should fix this issue has been merged.

Thanks again for reporting this issue.

**Closed as completed by Kami** 2019-08-09 13:42 UTC
Labels: api: storage, drivers: backblaze b2, issue: bug
